---
exclude_paths:
  - "tests/*"
  - "examples/*"
  - "examples/src/*"
  - "examples/src/utils/*"
  - "examples/src/providers/*"
  - "examples/src/providers/blockfrost/*"
  - "examples/src/providers/blockfrost/common/*"
  - "examples/src/providers/blockfrost/parsers/*"
  - "fuzz/*"
  - "scripts/*"
  - "doc/*"
  - "project_catalyst/*"
  - "cmake/*"
  - "assets/*"
  - "lib/external/*"