# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
    - cmake
    - libsodium-dev
  jobs:
    post_create_environment:
      - pip install sphinx sphinx-immaterial breathe
    post_install:
      - ./scripts/create-docs-makefiles.sh
    post_build:
      - pwd
      - ls -R
      - find ../../../_readthedocs/html -type f -exec sed -i 's/C++/C/g' {} \;
      - find ../../../_readthedocs/html -type f -exec sed -i 's/CPP/C/g' {} \;

sphinx:
  configuration: build/release/doc/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: doc/sphinx/requirements.txt