#!/bin/sh
#
# File: clean.sh
#
# Date: Sep 09, 2023
# Author: angel.castillo
#
# Copyright 2023 Biglup Labs
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ -f Makefile ]; then
  echo "Running make clean..."
  make clean
fi

# deletes backup files
echo "Removing backup files..."

find ./ -type f -name "*~" -exec rm -f {} \;
find ./ -type f -name "config.h" -exec rm -f {} \;

# deletes build system generated files
echo "Removing generated files by the build system..."

$( rm -rf build &> /dev/null )
$( rm -rf CMakeFiles &> /dev/null )
$( rm -rf _CPack_Packages &> /dev/null )
$( rm -rf Testing &> /dev/null )

$( rm -rf CPack* &> /dev/null )
$( rm -rf CMakeCache.txt &> /dev/null )
$( rm -rf install_manifest*.txt &> /dev/null )
$( rm -rf cmake_install.cmake &> /dev/null )
$( rm -rf CTestTestfile.cmake &> /dev/null )
$( rm -rf DartConfiguration.tcl &> /dev/null )
$( rm -rf Makefile &> /dev/null)
$( rm -rf install_manifest.txt &> /dev/null )
$( rm -rf *.ninja &> /dev/null )
$( rm -rf .ninja* &> /dev/null )
$( rm -rf logfile &> /dev/null )
$( rm -rf arch.c &> /dev/null )
$( rm -rf doxyfile &> /dev/null )

echo "Done removing files generated by the build system"
