SET (CMAKE_INSTALL_BINDIR_DOC        "User executables [PREFIX/bin]")
SET (CMAKE_INSTALL_DATADIR_DOC       "Read-only architecture-independent data [PREFIX/share]")
SET (CMAKE_INSTALL_SYSCONFDIR_DOC    "Read-only single-machine data [PREFIX/etc]")
SET (CMAKE_INSTALL_LOCALSTATEDIR_DOC "Modifiable single-machine data [PREFIX/var]")
SET (CMAKE_INSTALL_LIBDIR_DOC        "Object code libraries [PREFIX/lib]")
SET (CMAKE_INSTALL_MANDIR_DOC        "Manuals documentation [PREFIX/man]")

SET (CMAKE_INSTALL_BINDIR        "${CMAKE_INSTALL_PREFIX}/bin"   CACHE PATH ${CMAKE_INSTALL_BINDIR_DOC})
SET (CMAKE_INSTALL_DATADIR       "${CMAKE_INSTALL_PREFIX}/share" CACHE PATH ${CMAKE_INSTALL_DATADIR_DOC})
SET (CMAKE_INSTALL_LIBDIR        "${CMAKE_INSTALL_PREFIX}/lib"   CACHE PATH ${CMAKE_INSTALL_LIBDIR_DOC})
SET (CMAKE_INSTALL_MANDIR        "${CMAKE_INSTALL_PREFIX}/man"   CACHE PATH ${CMAKE_INSTALL_MANDIR_DOC})

IF (${CMAKE_INSTALL_PREFIX} STREQUAL "/usr")
  SET (CMAKE_INSTALL_SYSCONFDIR    "/etc" CACHE PATH ${CMAKE_INSTALL_SYSCONFDIR_DOC})
  SET (CMAKE_INSTALL_LOCALSTATEDIR "/var" CACHE PATH ${CMAKE_INSTALL_LOCALSTATEDIR_DOC})
ELSE()
 SET (CMAKE_INSTALL_SYSCONFDIR    "${CMAKE_INSTALL_PREFIX}/etc"   CACHE PATH ${CMAKE_INSTALL_SYSCONFDIR_DOC})
 SET (CMAKE_INSTALL_LOCALSTATEDIR "${CMAKE_INSTALL_PREFIX}/var"   CACHE PATH ${CMAKE_INSTALL_LOCALSTATEDIR_DOC})
ENDIF ()

MARK_AS_ADVANCED(
  CMAKE_INSTALL_BINDIR
  CMAKE_INSTALL_DATADIR
  CMAKE_INSTALL_SYSCONFDIR
  CMAKE_INSTALL_LOCALSTATEDIR
  CMAKE_INSTALL_LIBDIR
  CMAKE_INSTALL_MANDIR
)
