name: Build and Unit Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    tags-ignore:
      - '*'
jobs:
  build_and_unit_tests_little_endian:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install cmake
          sudo apt install libgtest-dev
          sudo apt install clang-tidy

      - name: Setup Gtest
        run: |
          cd $(mktemp -d)
          cmake /usr/src/googletest
          make
          sudo make install
          cd -

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Build
        run: |
          ./scripts/create-debug-makefiles.sh
          make

      - name: Run Unit Tests
        run: |
          make test
          ctest -T Coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          exclude: lib/external
          codecov_yml_path: 'codecov.yml'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  build_and_unit_tests_big_endian:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Build & test on big-endian (s390x)
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: s390x
          distro: ubuntu22.04
          install: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
              build-essential cmake libgtest-dev clang-tidy m4
            # Build & install gtest
            cd "$(mktemp -d)"
            cmake /usr/src/googletest
            make -j"$(nproc)"
            make install
          run: |
            set -euo pipefail
            cd "$GITHUB_WORKSPACE"
            ./scripts/create-debug-makefiles.sh
            make -j"$(nproc)"
            make test