name: Build and Unit Tests
on: [push]
jobs:
  build_and_unit_tests_little_endian:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install cmake
          sudo apt install libgtest-dev
          sudo apt install clang-tidy

      - name: Setup Gtest
        run: |
          cd $(mktemp -d)
          cmake /usr/src/googletest
          make
          sudo make install
          cd -

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Build
        run: |
          ./scripts/create-debug-makefiles.sh
          make

      - name: Run Unit Tests
        run: |
          make test
          ctest -T Coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          exclude: lib/external
          codecov_yml_path: 'codecov.yml'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  build_and_unit_tests_big_endian:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: mips-unknown-linux-gnu
            toolchain: stable
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install cmake
          sudo apt install libgtest-dev
          sudo apt install clang-tidy
          sudo apt install m4

      - name: Setup Gtest
        run: |
          cd $(mktemp -d)
          cmake /usr/src/googletest
          make
          sudo make install
          cd -

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Build
        run: |
          ./scripts/create-debug-makefiles.sh
          make

      - name: Run Unit Tests
        run: |
          make test