name: Memory Leak Detection
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build_and_run_valgrind:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install cmake
          sudo apt install libgtest-dev
          sudo apt install dos2unix
          sudo apt install valgrind
          sudo apt install m4

      - name: Setup Sodium
        run: |
          cd $(mktemp -d)
          wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.19.tar.gz -O sodium.tar.gz
          tar -xzf sodium.tar.gz
          cp -rp ./libsodium-stable/* .
          ./configure CFLAGS=-fPIC CXXFLAGS=-fPIC --enable-shared --with-pic
          make && make check
          sudo make install
          cd -

      - name: Setup JSON-C
        run: |
          cd $(mktemp -d)
          wget https://github.com/json-c/json-c/archive/refs/tags/json-c-0.17-20230812.tar.gz -O json-c.tar.gz
          tar -xzf json-c.tar.gz
          cd ./json-c-json-c-0.17-20230812
          cmake .
          make
          sudo make install
          cd -

      - name: Setup GMP
        run: |
          cd $(mktemp -d)
          wget https://storage.googleapis.com/biglup/gmp-6.2.1.tar.xz -O gmp.tar.xz
          tar Jxf gmp.tar.xz
          cd ./gmp-6.2.1
          ./configure CFLAGS="-fPIC" CXXFLAGS="-fPIC" --enable-static=yes --enable-shared=no --with-pic
          make -j$(nproc)
          sudo make install
          cd -

      - name: Setup Gtest
        run: |
          cd $(mktemp -d)
          cmake /usr/src/googletest
          make
          sudo make install
          cd -

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "true"

      - name: Build
        run: |
          ./scripts/create-debug-makefiles.sh
          make

      - name: Run Unit Tests
        run: |
          chmod +x ./scripts/run-valgrind-on-changes.sh
          dos2unix ./scripts/run-valgrind-on-changes.sh
          ./scripts/run-valgrind-on-changes.sh